version: '3'

services:
  mysql-db:
    container_name: mysql-reg-log-app
    image: mysql:8.4.0
    restart: unless-stopped
    env_file:
      - ./server/.env
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306

  nestjs-app:
    container_name: nest-reg-log-app-server
    image: ghcr.io/plinom/nest-server:0.0.1
    env_file:
      - ./server/.env
    build:
      context: ./server/
      target: production
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
    stdin_open: true
    tty: true
    depends_on:
      - mysql-db

  nextjs-app:
    container_name: next-reg-log-app-client
    image: ghcr.io/plinom/nest-client:0.0.1
    env_file:
      - ./client/.env
    build:
      context: ./client/
      target: runner
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - nestjs-app
      - mysql-db

volumes:
  mysql:
