version: '3'

services:
  mysql-db:
    container_name: mysql-reg-log-app
    image: mysql:8.4.0
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  nestjs-app:
    container_name: nest-reg-log-app
    image: ghcr.io/plinom/nest-server:0.0.1
    build:
      context: .
      target: production
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
    environment:
      NODE_ENV: production
    stdin_open: true
    tty: true
    depends_on:
      - mysql-db

volumes:
  mysql:
