version: '3'

services:
  mysql-db:
    # container_name: mysql-reg-log-app
    image: mysql:8.4.0
    restart: unless-stopped
    env_file:
      - ./server/.env
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT

  nestjs-app:
    container_name: nest-reg-log-app-server
    image: ghcr.io/plinom/nest-server:0.0.1
    env_file:
      - ./server/.env
    build:
      context: ./server/
      target: production
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    depends_on:
      - mysql-db

  nextjs-app:
    container_name: next-reg-log-app-client
    image: ghcr.io/plinom/nest-client:0.0.1
    env_file:
      - ./client/.env
    build:
      context: ./client/
      target: runner
    restart: unless-stopped
    ports:
      - $NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    depends_on:
      - nestjs-app

volumes:
  mysql:
